// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd01K7_gcE_Z4ndBQHnlxgdMr6HunU-GU',
    appId: '1:1049513522764:web:d49381aaf88175e16666e9',
    messagingSenderId: '1049513522764',
    projectId: 'donate-doacoes',
    authDomain: 'donate-doacoes.firebaseapp.com',
    storageBucket: 'donate-doacoes.appspot.com',
    measurementId: 'G-TF5JSJJ77K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5VgWrt3LpeiuyuaGQHEkHMfUQjjyga8',
    appId: '1:1049513522764:android:bd63b1ba24f347cf6666e9',
    messagingSenderId: '1049513522764',
    projectId: 'donate-doacoes',
    storageBucket: 'donate-doacoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDagPlMPpVCeKo3ExeVX2oE0_KdeUVcMPI',
    appId: '1:1049513522764:ios:c7c907463311d8c46666e9',
    messagingSenderId: '1049513522764',
    projectId: 'donate-doacoes',
    storageBucket: 'donate-doacoes.appspot.com',
    iosClientId: '1049513522764-5ki447g9b1288rottjbn30kpjt6fajlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.donate',
  );
}
